var questionList:Array<Question> = [
    new Question("Qual é a massa atômica do hidrogênio?", ["1 u", "2 u", "3 u", "4 u"], 1),
    new Question("Quantos átomos de oxigênio estão presentes em uma molécula de água (H2O)?", ["1 átomo", "2 átomos", "3 átomos", "4 átomos"], 1),
    new Question("O que é a massa molar de uma substância?", ["A massa de um átomo isolado", "A soma das massas dos átomos em uma molécula", "A massa de um mol de átomos", "A massa de um mol de moléculas"], 3),
    new Question("Qual é o número de Avogadro?", ["6.022 x 10^23 átomos", "1.602 x 10^-19 C", "9.81 m/s^2", "3.14159265359"], 1),
    new Question("De acordo com a Lei da Conservação da Massa, o que acontece com a massa total durante uma reação química?", ["A massa total permanece a mesma", "A massa total diminui", "A massa total aumenta", "A massa total não é relevante em uma reação química"], 1),
    new Question("O que representa a sigla \"u\" usada na massa atômica?", ["Unidade de medida", "Unidade de tempo", "Unidade de temperatura", "Unidade de carga elétrica"], 1),
    new Question("Qual é o símbolo químico do hidrogênio?", ["Hg", "He", "H", "O"], 3),
    new Question("Qual é o número atômico do carbono?", ["6", "12", "4", "8"], 2),
    new Question("Qual é o gás mais abundante na atmosfera da Terra?", ["Nitrogênio", "Oxigênio", "Hélio", "Dióxido de carbono"], 1),
    new Question("Qual é o processo pelo qual uma substância passa diretamente do estado sólido para o gasoso, sem se tornar líquida primeiro?", ["Fusão", "Evaporação", "Sublimação", "Condensação"], 3),
    new Question("O que a estequiometria estuda na química?", ["As propriedades dos elementos", "A velocidade das reações químicas", "As proporções de substâncias em reações químicas", "A estrutura dos átomos"], 3),
    new Question("Qual é a massa molar do átomo de hidrogênio (H)?", ["1 g/mol", "4 g/mol", "16 g/mol", "32 g/mol"], 1),
    new Question("Quantos átomos de oxigênio estão presentes em uma molécula de dióxido de carbono (CO2)?", ["1 átomo", "2 átomos", "3 átomos", "4 átomos"], 2),
    new Question("Qual é a massa molar do dióxido de carbono (CO2)?", ["12 g/mol", "16 g/mol", "28 g/mol", "44 g/mol"], 4),
    new Question("Qual é a relação entre as massas de reagentes e produtos em uma reação química?", ["Não há relação", "A massa dos reagentes é sempre maior que a dos produtos", "A massa dos produtos é sempre maior que a dos reagentes", "As massas dos reagentes e produtos tem proporções fixas"], 4),
    new Question("O que é um coeficiente estequiométrico em uma equação química balanceada?", ["Um número que indica a temperatura da reação", "Um número que indica a pressão da reação", "Um número que equilibra a equação química", "Um número que indica a cor da substância"], 3),
    new Question("Qual é o rendimento real em uma reação química?", ["A quantidade máxima de produtos que pode ser obtida a partir dos reagentes", "A quantidade de produtos obtidos em uma reação", "A quantidade de energia absorvida na reação", "A quantidade de reagentes consumidos"], 1),
    new Question("O que é a massa atômica relativa de um elemento químico?", ["A massa de um átomo desse elemento", "A massa de um íon desse elemento", "A média das massas dos isótopos desse elemento ponderada por suas abundâncias", "A soma das massas dos elétrons desse elemento"], 3),
    new Question("Qual é a massa molar do hidróxido de sódio (NaOH)?", ["22.99 g/mol", "40.00 g/mol", "18.02 g/mol", "62.01 g/mol"], 2),
    new Question("Se você reage 2 mols de hidróxido de sódio (NaOH) com ácido clorídrico (HCl) para formar cloreto de sódio (NaCl) e água (H2O), quantos mols de NaCl serão produzidos?", ["1 mol", "2 mols", "3 mols", "4 mols"], 1),
    new Question("Qual é a massa molar do ácido sulfúrico (H2SO4)?", ["36.01 g/mol", "64.06 g/mol", "98.08 g/mol", "18.02 g/mol"], 3),
    new Question("O que é uma reação de decomposição?", ["Uma reação em que uma substância é formada a partir de duas ou mais substâncias", "Uma reação em que uma substância é quebrada em outras substâncias", "Uma reação em que a substância permanece inalterada", "Uma reação em que a substância é aquecida"], 2),
    new Question("Qual é a fórmula química do ácido clorídrico?", ["HCl", "NaOH", "H2SO4", "CO2"], 1),
    new Question("Quantos átomos de hidrogênio (H) estão presentes em 3 mols de amônia (NH3)?", ["6.022 x 10^23 átomos", "1.8066 x 10^24 átomos", "3.011 x 10^24 átomos", "4.816 x 10^24 átomos"], 2),
    new Question("Qual é o rendimento real em uma reação se você obtém 80g de produto a partir de 100g de reagente, e o rendimento teórico é de 90g?", ["80%", "90%", "100%", "110%"], 1),
    new Question("Supondo que o Leonardo é o melhor aluno da prof Camila, qual nota ele merece?", ["10 pontos", "a nota máxima", "5+5", "40/4"], null),
]